// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvzjjrrqoxcuwaikbjvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2empqcnJxb3hjdXdhaWtianZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzg5NDksImV4cCI6MjA2ODcxNDk0OX0._1CmxU8chVj_QUHmYo6ykRGLxotaguQG9cIlm4QG40E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});